version: '3.8'

services:
  express:
    image: ${DOCKER_IMAGE}
    container_name: express_container
    ports:
      - "80:3000"
    command: npm run pm2dev
    depends_on:
      - mariadb
    env_file:
      - .env
    environment:
      DB_HOST: mariadb
      DB_USER: ${DB_USER}         
      DB_PASS: ${DB_PASSWORD}    
      DB_NAME: ${DB_NAME}
      #mounting volume to not lose assets when container is restarted/updated
    volumes:
      - assets_data:/usr/src/app/assets
  mariadb:
    image: mariadb:latest
    container_name: mariadb_container
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:
  assets_data:
